mgmtp.a12.dataservices.client.configuration.base-url=http://localhost:${config.port:8080}/api
mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.relative-login.url=user/local/login
