/*
 * SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
 *
 * Copyright (c) 2012-2026 mgm technology partners GmbH
 *
 * Dual License
 * ------------
 * This source file is part of the mgm A12 Platform and available under
 * a choice of two different licenses:
 *
 * 1. Open-Source License – EUPL v1.2
 *    You may redistribute and/or modify this file under the terms of the
 *    European Union Public License, version 1.2 - see https://eupl.eu/.
 *
 * 2. Commercial License
 *    Alternatively, you may obtain a commercial license from
 *    mgm technology partners GmbH, that permits use of this software
 *    under different terms (including support and maintenance services).
 *
 *    Please contact a12-license@mgm-tp.com for more information.
 *
 * You must select and comply with exactly one of the above license options.
 *
 * Warranty Disclaimer (applies to either option)
 * ----------------------------------------------
 * THIS SOFTWARE IS PROVIDED “AS IS” AND WITHOUT WARRANTY OF ANY KIND,
 * WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
 * LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
 */
package com.mgmtp.a12.dataservices.model.bulkload;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.mgmtp.a12.dataservices.AbstractSpringContextIT;
import com.mgmtp.a12.dataservices.common.exception.BaseError;
import com.mgmtp.a12.dataservices.exception.ExceptionKeys;
import com.mgmtp.a12.dataservices.model.persistence.internal.jpa.entity.ModelHeaderEntity;

import lombok.extern.slf4j.Slf4j;

import static com.mgmtp.a12.dataservices.constants.DocumentModelConstants.ADDRESS_DOCUMENT_MODEL;
import static com.mgmtp.a12.dataservices.constants.DocumentModelConstants.BUSINESS_PARTNER_SUPER_MODEL;
import static com.mgmtp.a12.dataservices.constants.PathConstants.BUSINESS_PARTNER_SUPER_DOCUMENT_MODEL_PATH;
import static com.mgmtp.a12.dataservices.constants.PathConstants.BUSINESS_PARTNER_SUPER_WITH_METADATA_MODEL_PATH;

@Slf4j
public class ModelBulkImportIT extends AbstractSpringContextIT {

	private static final String ORIGINAL_VALUE = "original";
	private static final String OVERWRITTEN_VALUE = "overwritten";
	private static final String FORM_MODEL_VALUE = "form";

	public static final String DOCUMENT_MODEL_RESOLVER_FIELD = "documentModelResolver";
	private static final String MODELS_BULKLOAD_DIR = "/models-bulkload/bulkload";
	private static final String MODELS_BULKLOAD_CLASSPATH_PREFIX = "classpath:" + MODELS_BULKLOAD_DIR;
	// Zip and jar files are generated by gradle task before compile test java and written to build directory.
	private static final String MODELS_BULKLOAD_ZIP_JAR_PREFIX = "classpath:/bulkload";
	private static final String ADDRESS_FORM_MODEL = "AddressForm";

	private static final String DOCUMENT_MODEL_TYPE_PATH = MODELS_BULKLOAD_DIR + "/overwriting/%s/" + ADDRESS_DOCUMENT_MODEL + ".json";
	private static String DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT;
	private static String DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT;

	private static final String FORM_MODEL_TYPE_PATH = MODELS_BULKLOAD_DIR + "/overwriting/%s/" + ADDRESS_FORM_MODEL + ".json";
	private static String FORM_MODEL_TYPE_ORIGINAL_CONTENT;
	private static String FORM_MODEL_TYPE_OVERWRITTEN_CONTENT;

	@Autowired private ModelBulkImporter modelBulkImporter;

	@DataProvider
	public static Object[][] multiErrorPathProvider() {
		return new Object[][] {
			{ MODELS_BULKLOAD_CLASSPATH_PREFIX + "/modelsMultiError" },
			{ MODELS_BULKLOAD_ZIP_JAR_PREFIX + "/modelsMultiError.zip" },
			{ MODELS_BULKLOAD_ZIP_JAR_PREFIX + "/modelsMultiError.jar" }
		};
	}

	@DataProvider
	public static Object[][] multiModelsPath() {
		return new Object[][] {
			{ MODELS_BULKLOAD_CLASSPATH_PREFIX + "/models" },
			{ MODELS_BULKLOAD_ZIP_JAR_PREFIX + "/models.zip" },
			{ MODELS_BULKLOAD_ZIP_JAR_PREFIX + "/models.jar" }
		};
	}

	@DataProvider
	public static Object[][] duplicatePathProvider() {
		return new Object[][] {
			{ MODELS_BULKLOAD_CLASSPATH_PREFIX + "/modelsDuplicate" },
			{ MODELS_BULKLOAD_ZIP_JAR_PREFIX + "/modelsDuplicate.zip" },
			{ MODELS_BULKLOAD_ZIP_JAR_PREFIX + "/modelsDuplicate.jar" }
		};
	}

	@DataProvider
	public static Object[][] outOfRootPathProvider() {
		return new Object[][] {
			{ MODELS_BULKLOAD_CLASSPATH_PREFIX + "/models/includes/level2" },
		};
	}

	@BeforeClass
	public void beforeClass() {
		DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT = loadResourceFromClasspathAsString(String.format(DOCUMENT_MODEL_TYPE_PATH, ORIGINAL_VALUE));
		DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT = loadResourceFromClasspathAsString(String.format(DOCUMENT_MODEL_TYPE_PATH, OVERWRITTEN_VALUE));

		FORM_MODEL_TYPE_ORIGINAL_CONTENT = loadResourceFromClasspathAsString(String.format(FORM_MODEL_TYPE_PATH, ORIGINAL_VALUE));
		FORM_MODEL_TYPE_OVERWRITTEN_CONTENT = loadResourceFromClasspathAsString(String.format(FORM_MODEL_TYPE_PATH, OVERWRITTEN_VALUE));
	}

	@BeforeMethod
	public void setUp() throws Exception {
		super.cleanUpTestEnvironment();
	}

	@Test(dataProvider = "multiErrorPathProvider")
	public void importWithMultipleErrors(String path) {
		log.info("Processing {}", path);

		modelService.delete("BusinessPartnerSuperInclude4");

		ModelBulkImportException ex =
			Assert.expectThrows(ModelBulkImportException.class, () -> modelBulkImporter.doImport(path, new BulkImporterConfiguration()));

		List<BaseError> errors = ex.getErrors();
		assertContainsError(errors, ExceptionKeys.MODEL_DUPLICITY_ERROR_KEY, "Duplicate files for model BusinessPartnerSuper");
		assertContainsError(errors, ExceptionKeys.MODEL_NOT_FOUND_ERROR_KEY, "Document model [BusinessPartnerSuperInclude4] not found");
		assertContainsError(errors, ExceptionKeys.MODEL_ACCESS_DENIED_ERROR_KEY, "Access to model [Address] has been denied!");
		Assert.assertEquals(errors.size(), 3);
	}

	private void assertContainsError(List<BaseError> errors, String key, String msg) {
		Optional<BaseError> optional = errors.stream()
			.filter(e -> e.getShortMessage().getKey().equals(key))
			.findFirst();
		Assert.assertTrue(optional.isPresent(), "Exception '%s' is expected but not thrown".formatted(msg));
		Assert.assertEquals(optional.get().getShortMessage().getDefaultMessage(), msg);
	}

	@Test(dataProvider = "multiModelsPath")
	public void importWithPreventedOverwrite(String path) throws Exception {
		String modelContent = loadResourceFromClasspathAsString(BUSINESS_PARTNER_SUPER_DOCUMENT_MODEL_PATH);
		modelService.create(modelContent);
		String expectedModelContent = loadResourceFromClasspathAsString(BUSINESS_PARTNER_SUPER_WITH_METADATA_MODEL_PATH);
		JSONAssert.assertEquals(expectedModelContent,
			getModelStringContent(BUSINESS_PARTNER_SUPER_MODEL), false);
		log.info("Processing {}", path);
		BulkImporterConfiguration configuration = new BulkImporterConfiguration();
		configuration.setOverwriteDocumentModels(false);
		modelBulkImporter.doImport(path, configuration);
		JSONAssert.assertEquals(expectedModelContent, getModelStringContent(BUSINESS_PARTNER_SUPER_MODEL), false);
	}

	@DataProvider
	public static Object[][] chekModelTypeOverwritingProvider() {
		return new Object[][] {
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(true).overwriteDocumentModels(true).overwriteModels(FORM_MODEL_VALUE, true).build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_OVERWRITTEN_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(true).overwriteDocumentModels(true).overwriteModels(FORM_MODEL_VALUE, false).build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_ORIGINAL_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(true).overwriteDocumentModels(false).overwriteModels(FORM_MODEL_VALUE, true).build(), DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT, FORM_MODEL_TYPE_OVERWRITTEN_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(true).overwriteDocumentModels(false).overwriteModels(FORM_MODEL_VALUE, false).build(), DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT, FORM_MODEL_TYPE_ORIGINAL_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(false).overwriteDocumentModels(true).overwriteModels(FORM_MODEL_VALUE, true).build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_OVERWRITTEN_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(false).overwriteDocumentModels(true).overwriteModels(FORM_MODEL_VALUE, false).build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_ORIGINAL_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(false).overwriteDocumentModels(false).overwriteModels(FORM_MODEL_VALUE, true).build(), DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT, FORM_MODEL_TYPE_OVERWRITTEN_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(false).overwriteDocumentModels(false).overwriteModels(FORM_MODEL_VALUE, false).build(), DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT, FORM_MODEL_TYPE_ORIGINAL_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(true).overwriteDocumentModels(true).build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_OVERWRITTEN_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(true).overwriteDocumentModels(false).build(), DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT, FORM_MODEL_TYPE_OVERWRITTEN_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(false).overwriteDocumentModels(true).build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_ORIGINAL_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModelsDefault(false).overwriteDocumentModels(false).build(), DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT, FORM_MODEL_TYPE_ORIGINAL_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModels(FORM_MODEL_VALUE, true).build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_OVERWRITTEN_CONTENT },
				{ new BulkImporterConfigurationBuilder().overwriteModels(FORM_MODEL_VALUE, false).build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_ORIGINAL_CONTENT },
				{ new BulkImporterConfigurationBuilder().build(), DOCUMENT_MODEL_TYPE_OVERWRITTEN_CONTENT, FORM_MODEL_TYPE_OVERWRITTEN_CONTENT }
		};
	}

	@Test(dataProvider = "chekModelTypeOverwritingProvider")
	public void chekModelTypeOverwriting(
			BulkImporterConfiguration configuration, String documentModelTypeContentExpected, String formModelTypeContentExpected
	) throws IOException, URISyntaxException {
		assertOverwrite(DOCUMENT_MODEL_TYPE_ORIGINAL_CONTENT, FORM_MODEL_TYPE_ORIGINAL_CONTENT, new BulkImporterConfiguration(), ORIGINAL_VALUE);
		assertOverwrite(documentModelTypeContentExpected, formModelTypeContentExpected, configuration, OVERWRITTEN_VALUE);
	}

	private void assertOverwrite(String addressModelContentExpected, String defaultModelContentExpected, BulkImporterConfiguration configuration, String suffix)
			throws IOException, URISyntaxException {
		modelBulkImporter.doImport(MODELS_BULKLOAD_CLASSPATH_PREFIX + "/overwriting/" + suffix, configuration);
		JSONAssert.assertEquals(addressModelContentExpected, getModelStringContent(ADDRESS_DOCUMENT_MODEL), true);
		JSONAssert.assertEquals(defaultModelContentExpected, getModelStringContent(ADDRESS_FORM_MODEL), true);
	}

	@Test(dataProvider = "multiModelsPath")
	public void testImport(String path) throws URISyntaxException, IOException {
		log.info("Processing {}", path);
		modelBulkImporter.doImport(path, new BulkImporterConfiguration());
		assertContent();
	}

	private void assertContent() {
		Assert.assertEquals(modelHeaderJpaRepository.findAll()
				.stream()
				.map(ModelHeaderEntity::getId)
				.collect(Collectors.toSet()),
			Set.of("AddressOther", "Address", "Contract", "BusinessPartnerSuperInclude1", "BusinessPartnerSuperInclude2", "BusinessPartnerSuperInclude3",
				"BusinessPartnerSuperInclude4", "BusinessPartnerSuperInclude5", "BusinessPartnerSuperOther", "BusinessPartnerSuper", "DemoModelBare",
				"DemoModelWithAllFields")
		);

		Assert.assertEquals(getModelStringContent("DemoModelBare"), loadResourceFromClasspathAsString(MODELS_BULKLOAD_DIR + "/models/jsonModelBase.json"));
		Assert.assertEquals(getModelStringContent("DemoModelWithAllFields"),
			loadResourceFromClasspathAsString(MODELS_BULKLOAD_DIR + "/models/jsonModelFull.json"));
	}

	@Test(dataProvider = "duplicatePathProvider")
	public void testImportDuplicate(String path) {
		log.info("Processing {}", path);

		ModelBulkImportException ex =
			Assert.expectThrows(ModelBulkImportException.class, () -> modelBulkImporter.doImport(path, new BulkImporterConfiguration()));

		List<BaseError> errors = ex.getErrors();
		Assert.assertFalse(errors.isEmpty());
		BaseError error = errors.get(0);
		Assert.assertTrue(error.getShortMessage().getDefaultMessage().matches("Duplicate files for model .*"));
	}

	@Test
	public void testImportWithoutDocumentModelResolver() {
		runWithFieldOverwritten(DOCUMENT_MODEL_RESOLVER_FIELD, null, modelBulkImporter, () -> {
			String path = MODELS_BULKLOAD_CLASSPATH_PREFIX + "/fsRootInclude";
			log.info("Processing {}", path);

			ModelBulkImportException ex =
				Assert.expectThrows(ModelBulkImportException.class, () -> modelBulkImporter.doImport(path, new BulkImporterConfiguration()));

			List<BaseError> errors = ex.getErrors();
			Assert.assertFalse(errors.isEmpty());
			BaseError error = errors.get(0);
			Assert.assertEquals(error.getShortMessage().getDefaultMessage(), "Cannot resolve included model [BusinessPartnerInvalidInclude]");
		});
	}

	@Test(dataProvider = "outOfRootPathProvider")
	public void testOutOfRootPath(String path) {
		log.info("Processing {}", path);

		ModelBulkImportException ex =
			Assert.expectThrows(ModelBulkImportException.class, () -> modelBulkImporter.doImport(path, new BulkImporterConfiguration()));

		List<BaseError> errors = ex.getErrors();
		Assert.assertFalse(errors.isEmpty());
		BaseError error = errors.get(0);
		Assert.assertTrue(error.getShortMessage().getDefaultMessage().matches("Document model \\[BusinessPartnerSuperInclude4] not found"));
	}

	private String getModelStringContent(String modelId) {
		return genericModelLoader.loadModel(modelId)
			.getContent()
			.getRawContent()
			.replace("\r\n", "\n");
	}

	private static class BulkImporterConfigurationBuilder {
		private final BulkImporterConfiguration config = new BulkImporterConfiguration();

		public BulkImporterConfigurationBuilder overwriteModelsDefault(boolean value) {
			config.setOverwriteModelsDefault(value);
			return this;
		}

		public BulkImporterConfigurationBuilder overwriteDocumentModels(boolean value) {
			config.setOverwriteDocumentModels(value);
			return this;
		}

		public BulkImporterConfigurationBuilder overwriteModels(String modelType, boolean value) {
			config.setOverwriteModels(modelType, value);
			return this;
		}

		public BulkImporterConfiguration build() {
			return config;
		}
	}

}
