mgmtp.a12.dataservices.attachments.ext.contentstore.embedded.enabled=false
mgmtp.a12.dataservices.contentstore.server.api.enabled=true
mgmtp.a12.dataservices.contentstore.client.configuration.remote-url=http://${config.contentstore.host:localhost}:${config.contentstore.port:9090}/cs
mgmtp.a12.dataservices.attachments.thumbnail.optimization.baseUrl=${mgmtp.a12.dataservices.contentstore.client.configuration.remote-url}
