spring.cache.type=none
spring.datasources.dataservices.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.datasources.dataservices.jpa.properties.hibernate.cache.use_query_cache=false
spring.datasources.dataservices.jpa.properties.hibernate.cache.region.factory_class=none
spring.datasources.dataservices.jpa.properties.hibernate.cache.hazelcast.instance_name=none
