mgmtp.a12.dataservices.attachments.ext.contentstore.embedded.enabled=true
mgmtp.a12.dataservices.contentstore.server.api.enabled=false
mgmtp.a12.dataservices.contentstore.server.contextPath=/cs
mgmtp.a12.dataservices.contentstore.base-url=http://localhost:${server.port:8080}
mgmtp.a12.dataservices.attachments.thumbnail.optimization.baseUrl=${mgmtp.a12.dataservices.contentstore.base-url}${mgmtp.a12.dataservices.contentstore.server.contextPath}
