mgmtp.a12.uaa.authorization.authorizationDefinition=classpath:/uaa/authorizationDefinition.json
mgmtp.a12.uaa.authentication.backend.enabled=true
mgmtp.a12.uaa.authentication.backend.grant-super-user-privileges.enabled=true
mgmtp.a12.uaa.authentication.secured-contexts=/actuator/**
mgmtp.a12.uaa.authentication.unsecured.urls=/api/attachment/thumbnail/**,/cs/download/**,/api/monitored-properties,/actuator/health/**
