spring.datasources.dataservices.liquibase.enabled=false
mgmtp.a12.dataservices.initialization.import.models.enabled=false
mgmtp.a12.dataservices.initialization.scripts.jsonRpc.enabled=false
mgmtp.a12.dataservices.initialization.migration.enabled=false
