spring.datasources.dataservices.embedded-postgres.enabled=true
spring.datasources.dataservices.jpa.database=postgresql
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
