spring.cache.type=hazelcast
spring.hazelcast.config=classpath:hazelcast.xml
spring.hazelcast.instance.name=A12S
spring.datasources.dataservices.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.datasources.dataservices.jpa.properties.hibernate.cache.use_query_cache=false
spring.datasources.dataservices.jpa.properties.hibernate.cache.region.factory_class=com.hazelcast.hibernate.HazelcastCacheRegionFactory
spring.datasources.dataservices.jpa.properties.hibernate.cache.hazelcast.instance_name=A12S
