mgmtp.a12.uaa.authentication.types=LOCAL
mgmtp.a12.uaa.authentication.principal.local-config.user-resources=classpath:localAuth/users/admin.yaml,classpath:localAuth/users/guest.yaml
mgmtp.a12.uaa.authentication.principal.access-rights-resource=classpath:localAuth/roles.yaml
