### --- LOGGING ---
logging.level.root=WARN
logging.level.com.mgmtp.a12.dataservices.client.cli=INFO

### --- UAA ---
mgmtp.a12.uaa.authentication.client.rest.uaa-base.url=http://localhost:${config.port:8080}/api
mgmtp.a12.uaa.authentication.client.rest.token-type=HEADER
mgmtp.a12.uaa.authentication.client.rest.authorizationDataStore=file:${user.home}/.a12cli.uaa_token
