spring.profiles.active=dataservices-uaa,dataservices-core-test-local_auth,dataservices-external_postgres,dataservices-embedded_contentstore,contentstore-external_postgres,dataservices-actuators,dataservices-rpc,dataservices-core-test-test_logging

mgmtp.a12.dataservices.logging.anonymization.enabled=false
mgmtp.a12.dataservices.attachments.thumbnail.preview.enabled=true

### --- UAA ---
workDir=
mgmtp.a12.uaa.authentication.unsecured.urls=/api/attachment/thumbnail/**,/cs/download/**,/console/**,/actuator/**,/api/monitored-properties
mgmtp.a12.uaa.authentication.principal.additional-properties=firstname,lastname,email
mgmtp.a12.uaa.authentication.cors.enable=false
mgmtp.a12.uaa.authentication.context-path=/api
