management.endpoints.access.default=read-only
management.endpoints.web.exposure.include=*
management.endpoint.health.showDetails=always
management.health.defaults.enabled=true
management.health.ldap.enabled=false
