mgmtp.a12.dataservices.contentstore.storage.content-storage=FS
mgmtp.a12.dataservices.contentstore.limit-size=10 MiB
mgmtp.a12.dataservices.contentstore.base-url=http://localhost:${server.port:8080}
mgmtp.a12.dataservices.contentstore.server.api.enabled=true
### --- JPA ---
spring.jta.enabled=true
spring.datasources.contentstore.jpa.show-sql=false
spring.datasources.contentstore.jpa.properties.hibernate.ddl-auto=validate
spring.datasources.contentstore.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.datasources.contentstore.jpa.properties.hibernate.cache.use_query_cache=false
spring.datasources.contentstore.jpa.properties.hibernate.cache.region.factory_class=com.hazelcast.hibernate.HazelcastCacheRegionFactory
spring.datasources.contentstore.jpa.properties.hibernate.cache.hazelcast.instance_name=A12S
spring.datasources.contentstore.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.datasources.contentstore.jpa.properties.hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
### --- LIQUIBASE ---
spring.datasources.contentstore.liquibase.enabled=true
spring.datasources.contentstore.liquibase.change-log=classpath:/contentstore_db/project_model.xml
