# Default profile
spring.profiles.default=contentstore-example-common

spring.profiles.group.contentstore-example-common=contentstore-uaa,\
  contentstore-embedded_h2,\
  contentstore-actuators, \
  contentstore-example-uaa

spring.profiles.group.contentstore-example-trust-external-mime-type-env=contentstore-example-common,contentstore-example-content-external-mime-type

spring.profiles.group.contentstore-example-http1-env=contentstore-example-common,contentstore-http1-only
