mgmtp.a12.uaa.authentication.jwt.secret=YXNkZmdoamtscXdlcnR6dWlvcHl4Y3Zibm0xMjM0NTY=
mgmtp.a12.uaa.authentication.jwt.privateKeyLocation=classpath:/uaa_private_key.pem
mgmtp.a12.uaa.authentication.jwt.publicKeyLocation=classpath:/uaa_public_key.pem
mgmtp.a12.uaa.authentication.types=UAA_ACCESS_TOKEN
