# Default profile
spring.profiles.default=contentstore-example-common

spring.profiles.group.contentstore-example-common=\
  contentstore-uaa,\
  contentstore-embedded_h2,\
  contentstore-actuators, \
  contentstore-example-uaa

spring.profiles.group.contentstore-example-trust-external-mime-type_env=\
  contentstore-example-common,\
  contentstore-example-content_external_mime_type

spring.profiles.group.contentstore-example-http1_env=\
  contentstore-example-common,\
  contentstore-http1_only
