mgmtp.a12.dataservices.contentstore.client.configuration.remote-url=http://localhost:${config.port:8080}/cs
mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.relative-login.url=user/local/login
