spring.banner.location=classpath:/banner.txt

logging.file.name=dataservices-server.log
logging.pattern.console=%d{ISO8601} [%-20.20t][%-5p][%-40.40c][u:%X{user}] - %m%n
logging.pattern.file=%d{ISO8601} [%-20.20t][%-5p][%-40.40c][u:%X{user}] - %m%n

logging.level.com.mgmtp.a12.dataservices=INFO
logging.level.com.mgmtp.a12.validation=INFO
logging.level.com.hazelcast=WARN
logging.level.com.googlecode.jsonrpc4j.JsonRpcBasicServer=ERROR
# SqlExceptionHelper reveal user data at ERROR level, which is a security issue
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=OFF

server.http2.enabled=true
