mgmtp.a12.dataservices.initialization.scripts.jsonRpc.enabled=true
mgmtp.a12.dataservices.initialization.scripts.jsonRpc.paths=classpath:profile_specific/example_custom_type_profile/rpc/importPeopleScript.json
