### --- Liquibase ---
spring.datasources.dataservices.liquibase.change-log=classpath:/db/example_liquibase.xml

### --- Logging ---
logging.level.com.googlecode.jsonrpc4j=DEBUG
logging.level.liquibase=WARN
logging.level.org.liquibase=WARN
logging.level.com.hazelcast=WARN
logging.level.org.springframework=WARN
mgmtp.a12.dataservices.logging.anonymization.enabled=false

### --- MODELS ---
mgmtp.a12.dataservices.models.list.hard-limit=2
mgmtp.a12.dataservices.documents.validation.list.hard-limit=2

### --- DOCUMENTS ---
mgmtp.a12.dataservices.documents.validation.enabled=true
mgmtp.a12.dataservices.documents.validation.partial-for-models=BusinessPartner
mgmtp.a12.dataservices.documents.validation.skip-for-models=Address
mgmtp.a12.dataservices.documents.computation.enabledForModels=ComputationModel, BusinessPartner, CoInsuredAdditionalFields, ContractCDM

### --- OTHER ---
mgmtp.a12.dataservices.initialization.import.models.overwrite.models.DomainProduct=false
mgmtp.a12.dataservices.initialization.import.models.overwrite.models.DomainBrand=false

### --- ATTACHMENTS ---
mgmtp.a12.dataservices.attachments.rest-endpoint.enabled=true
mgmtp.a12.dataservices.attachments.thumbnail.preview.enabled=true
mgmtp.a12.dataservices.jobs.attachments.temporary.expireHours=72
mgmtp.a12.dataservices.attachments.cleanup.retry.max=1
mgmtp.a12.dataservices.attachments.cleanup.retry.delay=5 s

### --- RPC ---
mgmtp.a12.dataservices.json-rpc.max-method-calls-per-request=500

### --- QUERY ---
mgmtp.a12.dataservices.query.simpleSearch.minSearchableTokenSize=2
mgmtp.a12.dataservices.query.maxOrOperands=5
mgmtp.a12.dataservices.query.maxOrOperators=10
mgmtp.a12.dataservices.query.maxAndOperands=5
mgmtp.a12.dataservices.query.maxAndOperators=10
