# Default profile
spring.profiles.default=dataservices-example-common

spring.profiles.group.dataservices-example-common=\
  dataservices-uaa,\
  dataservices-external_postgres,\
  contentstore-external_postgres,\
  dataservices-embedded_contentstore,\
  dataservices-rpc,\
  dataservices-actuators,\
  dataservices-example-shared,\
  dataservices-example-uaa,\
  dataservices-example-sme_workspace

spring.profiles.group.dataservices-example-attachments_env=\
  dataservices-example-common,\
  dataservices-example-attachments

spring.profiles.group.dataservices-example-authorization_env=\
  dataservices-example-common

spring.profiles.group.dataservices-example-authorization-uaa_env=\
  dataservices-example-common,\
  dataservices-example-authorization_uaa

spring.profiles.group.dataservices-example-custom-type_env=\
  dataservices-example-common, \
  dataservices-example-custom_type
