mgmtp.a12.dataservices.seed-data.delete.enabled=true
mgmtp.a12.dataservices.seed-data.export.enabled=true
mgmtp.a12.dataservices.seed-data.import.enabled=true

# to enable seed data initialization, you must define the 2 properties below:
#mgmtp.a12.dataservices.initialization.seed-data.enabled=true
#mgmtp.a12.dataservices.initialization.seed-data.seed-file.path=/path/to/seed_data.tar.gz
