mgmtp.a12.dataservices.contentstore.limit-size=100 MiB
mgmtp.a12.dataservices.contentstore.enableDefaultDownloadListener=false
mgmtp.a12.dataservices.attachments.enabled=true
mgmtp.a12.dataservices.attachments.rest-endpoint.enabled=true
