# to use this profile, please change document metadata file name from `/com/mgmtp/a12/platform/model/document-meta-data-extension.json` to `/com/mgmtp/a12/platform/model/document-meta-data.json`
com.mgmtp.a12.examples.documents.metadata.enabled=true
mgmtp.a12.dataservices.models.metadata.document.path=/com/mgmtp/a12/platform/model/document-meta-data-extension.json
