mgmtp.a12.uaa.authentication.types=LOCAL
mgmtp.a12.uaa.authentication.principal.local-config.user-resources=classpath:authorization/users/admin.yaml,classpath:authorization/users/guest.yaml,classpath:authorization/users/ActuatorUser.yaml,classpath:authorization/users/tester.yaml,classpath:authorization/users/TestAdmin.yaml
mgmtp.a12.uaa.authentication.principal.access-rights-resource=classpath:authorization/userTestRoles.yaml
mgmtp.a12.uaa.authorization.child-authorization-definitions=classpath:authorization/additionalAuthorizationDefinition.json

mgmtp.a12.uaa.authentication.principal.additional-properties=firstname,lastname,email
mgmtp.a12.uaa.authentication.jwt.secret=YXNkZmdoamtscXdlcnR6dWlvcHl4Y3Zibm0xMjM0NTY=
mgmtp.a12.uaa.authentication.jwt.privateKeyLocation=classpath:/uaa_private_key.pem
mgmtp.a12.uaa.authentication.jwt.publicKeyLocation=classpath:/uaa_public_key.pem
mgmtp.a12.uaa.authentication.unsecured.urls=/api/attachment/thumbnail/**,/cs/download/**,/console/**,/actuator/**,/api/internal/seed-data,/api/monitored-properties
mgmtp.a12.uaa.authentication.context-path=/api
