mgmtp.a12.dataservices.attachments.mimeType.probeMimeType.enabled=true
mgmtp.a12.dataservices.attachments.mimeType.inMemoryTemp.enabled=true
mgmtp.a12.uaa.authentication.client.rest.authentication-type=DELEGATED
mgmtp.a12.dataservices.attachments.enabled=true
mgmtp.a12.dataservices.attachments.rest-endpoint.enabled=true
