mgmtp.a12.dataservices.sme-workspace.delete.enabled=true
mgmtp.a12.dataservices.sme-workspace.export.enabled=true
mgmtp.a12.dataservices.sme-workspace.import.enabled=true

# to enable SME Workspace initialization, you must define the 2 properties below:
#mgmtp.a12.dataservices.initialization.sme-workspace.enabled=true
#mgmtp.a12.dataservices.initialization.sme-workspace.seed-file.path=/path/to/sme_workspace.tar.gz
