mgmtp.a12.uaa.authorization.childAuthorizationDefinitions=classpath:/profile_specific/example_authorization_uaa_profile/abacAuthorizationDefinition.json

mgmtp.a12.uaa.authentication.jwt.store-user-in-token.enabled=true
mgmtp.a12.uaa.authentication.principal.access-rights-resource=classpath:profile_specific/example_authorization_uaa_profile/roles.yaml
mgmtp.a12.uaa.authentication.principal.local-config.user-resources=classpath:profile_specific/example_authorization_uaa_profile/users/*.yaml,classpath:authorization/users/admin.yaml
mgmtp.a12.uaa.authentication.principal.additional-properties=maxContractValue, minIncome, restrictedCity

mgmtp.a12.dataservices.initialization.import.models.enabled=true
mgmtp.a12.dataservices.initialization.import.models.path=classpath:/profile_specific/example_authorization_uaa_profile/model/

mgmtp.a12.dataservices.initialization.scripts.jsonRpc.enabled=true
mgmtp.a12.dataservices.documents.validation.enabled=true
mgmtp.a12.dataservices.documents.validation.partial-for-models=BusinessPartner
mgmtp.a12.dataservices.initialization.scripts.jsonRpc.paths=classpath:/profile_specific/example_authorization_uaa_profile/rpc/importDocuments.json

logging.level.com.mgmtp.a12.uaa.authorization.security=DEBUG
logging.level.com.mgmtp.a12.dataservices.query=DEBUG
