mgmtp.a12.uaa.authorization.childAuthorizationDefinitions=classpath:profiles/authorization/authorizationDefinition.json,classpath:additionalAuthorizationDefinition.json
mgmtp.a12.uaa.authentication.principal.access-rights-resource=classpath:profiles/authorization/roles.yaml
mgmtp.a12.uaa.authentication.principal.local-config.user-resources=classpath:profiles/authorization/users/*.yaml,classpath:users/admin.yaml
mgmtp.a12.uaa.authentication.principal.additional-properties=firstname,lastname,email,brand
logging.level.com.mgmtp.a12.uaa.authorization.security=DEBUG
