com.mgmtp.a12.examples.attachments.virusScan.enabled=true
com.mgmtp.a12.examples.attachments.virusScan.clamAV.host=localhost
com.mgmtp.a12.examples.attachments.virusScan.clamAV.port=3310
com.mgmtp.a12.examples.attachments.virusScan.clamAV.timeout=2000
