# Default profile
spring.profiles.default=dataservices-example-common

spring.profiles.group.dataservices-example-common=\
  dataservices-uaa,\
  dataservices-external_postgres,\
  contentstore-external_postgres,\
  dataservices-embedded_contentstore,\
  dataservices-rpc,\
  dataservices-actuators,\
  dataservices-example-shared,\
  dataservices-example-uaa,\
  dataservices-example-seed-data,\
  dataservices-example-custom-operator

spring.profiles.group.dataservices-example-attachments_env=\
  dataservices-example-common,\
  dataservices-example-import_models,\
  dataservices-example-attachments

spring.profiles.group.dataservices-example-authorization_env=\
  dataservices-example-common,\
  dataservices-example-import_models

spring.profiles.group.dataservices-example-abac_env=\
  dataservices-example-common,\
  dataservices-example-abac

spring.profiles.group.dataservices-example-customType_env=\
  dataservices-example-common,\
  dataservices-example-import_models,\
  dataservices-example-custom_type

spring.profiles.group.dataservices-example-probes_attachment_mime_type_env=\
  dataservices-uaa,\
  dataservices-external_postgres,\
  dataservices-standalone_contentstore,\
  dataservices-rpc,\
  dataservices-actuators,\
  dataservices-example-shared,\
  dataservices-example-uaa,\
  dataservices-example-attachments_probes_mime_type

spring.profiles.group.dataservices-example-http1-env=\
  dataservices-example-common,\
  dataservices-http1-only

spring.profiles.group.dataservices-example-attachments-thumbnail-graphic2d_env=\
  dataservices-example-common,\
  dataservices-example-import_models,\
  dataservices-example-attachments-thumbnail-graphic2d

spring.profiles.group.dataservices-example-attachments-thumbnail-thumbnailator-conserve-memory_env=\
  dataservices-example-common,\
  dataservices-example-import_models,\
  dataservices-example-attachments-thumbnail-thumbnailator

spring.profiles.group.dataservices-example-attachments-thumbnail-disk-cache_env=\
  dataservices-example-common,\
  dataservices-example-import_models,\
  dataservices-example-attachments-thumbnail-disk-cache

spring.profiles.group.dataservices-example-custom-operator_env=\
  dataservices-example-common,\
  dataservices-example-import_models,\
  dataservices-example-custom-operator
