com.mgmtp.a12.examples.attachments.mime-types.custom.enabled=true
com.mgmtp.a12.examples.attachments.mime-types.custom.mime-type=application/zip
com.mgmtp.a12.examples.attachments.mime-types.custom.replacement=zip1
