### --- JPA ---
spring.datasources.dataservices.jpa.properties.hibernate.cache.use_second_level_cache=false

### --- INITIALIZATION
mgmtp.a12.dataservices.initialization.migration.enabled=true

### --- JOBS ---
mgmtp.a12.dataservices.jobs.enabled=false
infinispan.embedded.enabled=false
