spring.profiles.active=dataservices-embedded_contentstore,dataservices-external_postgres,dataservices-uaa

### --- Initialization ---
spring.datasources.dataservices.jpa.properties.hibernate.cache.use_second_level_cache=false

### --- Migration ---
mgmtp.a12.dataservices.initialization.migration.enabled=true

### --- Jobs
mgmtp.a12.dataservices.jobs.enabled=false
