mgmtp.a12.uaa.authentication.principal.local-config.user-resources=classpath:local_users/ActuatorUser.yaml,\
  classpath:local_users/Admin.yaml,\
  classpath:local_users/Guest.yaml,\
  classpath:local_users/ModelCreateUser.yaml,\
  classpath:local_users/ModelUpdateUser.yaml,\
  classpath:local_users/ModelReadUser.yaml,\
  classpath:local_users/ModelDeleteUser.yaml,\
  classpath:local_users/ModelManagerUser.yaml,\
  classpath:local_users/NoAccessRightsUser.yaml,\
  classpath:local_users/NotTest.yaml,\
  classpath:local_users/Test.yaml,\
  classpath:local_users/Test.yaml,\
  classpath:local_users/TestAdmin.yaml,\
  classpath:local_users/Tester.yaml,\
  classpath:local_users/TestUserWithSpaces.yaml,\
  classpath:local_users/DocumentReadUser.yaml,\
  classpath:local_users/DocumentWriteUser.yaml,\
  classpath:local_users/DocumentCreateUser.yaml,\
  classpath:local_users/DocumentUpdateUser.yaml,\
  classpath:local_users/DocumentPartialUpdateUser.yaml,\
  classpath:local_users/DocumentDeleteUser.yaml,\
  classpath:local_users/DocumentCopyUser.yaml
mgmtp.a12.uaa.authentication.principal.access-rights-resource=classpath:testUserRoles.yaml
mgmtp.a12.uaa.authentication.types=LOCAL
mgmtp.a12.uaa.authentication.jwt.secret=YXNkZmdoamtscXdlcnR6dWlvcHl4Y3Zibm0xMjM0NTY=
mgmtp.a12.uaa.authentication.jwt.expirationSeconds=86400
mgmtp.a12.uaa.authentication.jwt.privateKeyLocation=classpath:/uaa_private_key.pem
mgmtp.a12.uaa.authentication.jwt.publicKeyLocation=classpath:/uaa_public_key.pem
