mgmtp.a12.uaa.authentication.principal.localConfig.userResources=file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/ActuatorUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/Admin.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/Guest.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/ModelCreateUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/ModelUpdateUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/ModelReadUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/ModelDeleteUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/ModelManagerUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/NoAccessRightsUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/NotTest.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/Test.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/Test.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/TestAdmin.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/Tester.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/TestUserWithSpaces.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/DocumentReadUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/DocumentWriteUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/DocumentCreateUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/DocumentUpdateUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/DocumentPartialUpdateUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/DocumentDeleteUser.yaml,\
  file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/local_users/DocumentCopyUser.yaml
mgmtp.a12.uaa.authentication.principal.accessRightsResource=file:./dataservices-core-spring-boot-autoconfigure/src/testFixtures/resources/testUserRoles.yaml
mgmtp.a12.uaa.authentication.client.rest.authenticationType=LOCAL
mgmtp.a12.uaa.authentication.jwt.secret=YXNkZmdoamtscXdlcnR6dWlvcHl4Y3Zibm0xMjM0NTY=
mgmtp.a12.uaa.authentication.jwt.expirationSeconds=86400
mgmtp.a12.uaa.authentication.jwt.privateKeyLocation=file:./dataservices-core/src/testFixtures/resources/uaa_private_key.pem
mgmtp.a12.uaa.authentication.jwt.publicKeyLocation=file:./dataservices-core/src/testFixtures/resources/uaa_public_key.pem
mgmtp.a12.uaa.authentication.contextPath=/api
