#---
spring.config.activate.on-profile=dataservices-external_postgres
spring.datasources.dataservices.url=${DATASERVICES_DB_URL}
spring.datasources.dataservices.username=${DATASERVICES_DB_USERNAME}
spring.datasources.dataservices.password=${DATASERVICES_DB_PASSWORD}
spring.datasources.dataservices.hikari.minimumIdle=1
spring.datasources.dataservices.hikari.idleTimeout=10000
spring.datasources.dataservices.hikari.maxLifetime=30000

#---
spring.config.activate.on-profile=contentstore-external_postgres
spring.datasources.contentstore.url=${CONTENTSTORE_DB_URL}
spring.datasources.contentstore.username=${CONTENTSTORE_DB_USERNAME}
spring.datasources.contentstore.password=${CONTENTSTORE_DB_PASSWORD}
spring.datasources.contentstore.liquibase.database-change-log-lock-table=CS_DATABASECHANGELOGLOCK
spring.datasources.contentstore.liquibase.database-change-log-table=CS_DATABASECHANGELOG
spring.datasources.contentstore.hikari.minimumIdle=1
spring.datasources.contentstore.hikari.idleTimeout=10000
