# Use spring.config.import because this file is located in testFixtures
logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr([%15.15t]){faint} [%clr(${LOG_LEVEL_PATTERN:%5p})] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
#logging.level.root=WARN
logging.level.org.springframework.web=INFO
logging.level.com.mgmtp.a12.dataservices=DEBUG
logging.level.com.mgmtp.a12.validation=INFO
logging.level.com.mgmtp.a12.dataservices.common.events.internal.CommonDataServicesListenerMethodAdapter=WARN
logging.level.com.mgmtp.a12.common.jaxb.JaxbMarshaller=WARN
