mgmtp.a12.dataservices.documents.validation.language=en
mgmtp.a12.dataservices.actuatorSecurity.health=true
mgmtp.a12.dataservices.actuatorSecurity.secured.health=false

management.endpoints.access.default=none
management.health.defaults.enabled=false

spring.servlet.multipart.enabled=true
